cmpdev:
  host: https://cmp.cmpdev.crowncommercial.gov.uk/facilities-management
  account_username: otaikutoyin@gmail.com
  account_password: Test1234!
preview:
  host: https://cmp.fm-preview.crowncommercial.gov.uk/facilities-management
  account_username: autotest1@crowncommercial.gov.uk
  account_password: 1Pass2!?

